export enum OrderStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
<<<<<<< HEAD
  SHIPPED = 'SHIPPED',
  COMPLETED = 'COMPLETED',
=======
  ASSIGNED = 'ASSIGNED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
>>>>>>> f8787549117cce75ddd3b4459fd77c4f0f0ad9cb
  CANCELLED = 'CANCELLED',
}
