services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_NAME: api-gateway
    container_name: meds-api-gateway
    command: ["npm", "run", "start:dev", "--", "api-gateway"]
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: development
      GATEWAY_PORT: 3000
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 3529
      MEDICATION_SERVICE_HOST: medication-service
      MEDICATION_SERVICE_PORT: 3530
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - user-service
      - medication-service
    networks:
      - meds-network
  
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_NAME: user-service
    container_name: meds-user-service
    command: ["npm", "run", "start:dev", "--", "user-service"]
    env_file:
      - ./apps/user-service/.env
    environment:
      NODE_ENV: development
      USER_SERVICE_HOST: 0.0.0.0
      USER_SERVICE_PORT: 3529
    expose:
      - "3529"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - meds-network

  medication-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_NAME: medication-service
    container_name: meds-medication-service
    command: ["npm", "run", "start:dev", "--", "medication-service"]
    env_file:
      - ./apps/medication-service/.env
    environment:
      NODE_ENV: development
      MEDICATION_SERVICE_HOST: 0.0.0.0
      MEDICATION_SERVICE_PORT: 3530
    expose:
      - "3530"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - meds-network

  mongodb:
    image: mongo:latest
    container_name: meds-mongodb
    ports:
      - "27017:27017"
    networks:
      - meds-network

  redis:
    image: redis:alpine
    container_name: meds-redis
    ports:
      - "6379:6379"
    networks:
      - meds-network

networks:
  meds-network:
    driver: bridge